name: medialert
description: A medication reminder and tracking app.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  flutter_local_notifications: ^15.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  generate: true

