name: medialert
description: A medication reminder and tracking app.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  provider: ^6.1.1
  go_router: ^13.0.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  fl_chart: ^0.55.0
  pdf: ^3.8.1
  path_provider: ^2.0.11
  flutter_local_notifications: ^15.1.0+1
  flutter_secure_storage: ^9.0.0
  csv: ^5.1.1
  share_plus: ^7.2.1
  intl: ^0.19.0
  google_sign_in: ^6.1.6
  googleapis: ^12.0.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.12
  image_picker: ^1.0.7
  image_cropper: ^5.0.1
  cached_network_image: ^3.3.1
  flutter_image_compress: ^2.1.0
  easy_localization: ^3.0.3
  timeago: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  flutter_lints: ^3.0.1
  mockito: ^5.4.4
  mocktail: ^1.0.2
  test: ^1.24.9
  fake_async: ^1.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/

  generate: true

